[package]
name = "basic_hash_ring"
version = "0.2.0"
edition = "2024"
description = "A basic hash ring implementation"
license = "MIT"
repository = "https://github.com/danthegoodman1/basic_hash_ring"

[dependencies]
xxhash-rust = { version = "0.8.15", features = ["xxh3", "const_xxh3"] }
